defaults:
  - _base_
  - _self_
  - override launcher: torchrun

experiment_name: fp16+peft+bnb-4bit+dp=2

launcher:
  nproc_per_node: 2
  rdzv_endpoint: localhost:29511

backend:
  quantization_scheme: bnb
  quantization_config:
    load_in_4bit: true
    bnb_4bit_compute_dtype: float16
  peft_strategy: lora
  peft_config:
    task_type: CAUSAL_LM

hydra:
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: 0,1
