defaults:
  - _base_
  - _self_
  - override launcher: torchrun

experiment_name: fp16+fsdp=2

launcher:
  nproc_per_node: 2
  rdzv_endpoint: localhost:29522

benchmark:
  training_arguments:
    fsdp: full_shard

hydra:
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: 0,1
