defaults:
  - _base_
  - _self_
  - override launcher: torchrun

experiment_name: fp16+peft+dp=2

launcher:
  nproc_per_node: 2
  rdzv_endpoint: localhost:29511

backend:
  peft_strategy: lora
  peft_config:
    task_type: CAUSAL_LM

hydra:
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: 0,1
