defaults:
  - _base_
  - _self_
  - override launcher: torchrun

experiment_name: fp16+dp=2

launcher:
  nproc_per_node: 2
  rdzv_endpoint: localhost:29500

hydra:
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: 0,1
