defaults:
  - _base_
  - _self_
  - override launcher: torchrun

experiment_name: fp16+peft+dp=2

launcher:
  nproc_per_node: 2
  rdzv_endpoint: localhost:29511

backend:
  peft_strategy: lora
  peft_config:
    task_type: CAUSAL_LM

benchmark:
  training_arguments:
    deepspeed:
      train_batch_size: auto
      train_micro_batch_size_per_gpu: auto
      zero_optimization:
        stage: 3

hydra:
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: 0,1
