defaults:
  - backend: pytorch # default backend
  - launcher: process # isolated launcher
  - benchmark: inference # default benchmark
  - experiment # inheriting from experiment config
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

hydra:
  run:
    dir: experiments/${oc.env:HOSTNAME}/${model}/${experiment_name}
  sweep:
    dir: experiments/${oc.env:HOSTNAME}/${model}/${experiment_name}
    subdir: ${benchmark.input_shapes.batch_size}
  job:
    chdir: true
    env_set:
      CUDA_VISIBLE_DEVICES: 0
      CUDA_DEVICE_ORDER: PCI_BUS_ID
  sweeper:
    params:
      benchmark.input_shapes.batch_size: 1,2,4,8,16,32,64,128
      model: NousResearch/Llama-2-7b-hf,NousResearch/Llama-2-13b-hf

experiment_name: ???
model: llama-2
device: cuda

backend:
  no_weights: true
  torch_dtype: float16
  continuous_isolation: true

benchmark:
  memory: true
  warmup_runs: 10
  new_tokens: 512
  input_shapes:
    batch_size: null
    sequence_length: 256
