defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: automatic_speech_recognition

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: openai/whisper-large-v3
  processor: openai/whisper-large-v3
  task: automatic-speech-recognition

scenario:
  dataset_name: EnergyStarAI/ASR
  num_samples: 1000
  audio_column_name: audio
  input_shapes:
    batch_size: 1
