defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: image_classification

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: google/vit-base-patch16-224
  task: image-classification

scenario:
  dataset_name: EnergyStarAI/image_classification
  num_samples: 1000
  image_column_name: image
  input_shapes:
    batch_size: 1
