defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

experiment_name: image_generation

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: false
  model: ByteDance/SDXL-Lightning
  task: stable-diffusion

scenario:
  dataset_name: EnergyStarAI/image_generation
  num_samples: 1000
  text_column_name: prompt
  input_shapes:
    batch_size: 1
