defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: object_detection

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: facebook/detr-resnet-50
  processor: facebook/detr-resnet-50
  task: object-detection

scenario:
  dataset_name: EnergyStarAI/object_detection
  num_samples: 1000
  image_column_name: image
  input_shapes:
    batch_size: 1
