defaults:
  - backend: pytorch # default backend
  - launcher: process # default launcher
  - benchmark: energy_star # default benchmark
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: object_detection

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: facebook/detr-resnet-50
  processor: facebook/detr-resnet-50
  task: object-detection

benchmark:
  dataset_name: EnergyStarAI/object_detection
  num_samples: 1000
  image_column_name: image
  input_shapes:
    batch_size: 1

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/${experiment_name}/${backend.model}/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    # where to store sweep results
    dir: sweeps/${experiment_name}/${backend.model}/${now:%Y-%m-%d-%H-%M-%S}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      # set environment variable OVERRIDE_BENCHMARKS to 1
      # to not skip benchmarks that have been run before
      OVERRIDE_BENCHMARKS: 1
