defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: summarization_t5

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: google-t5/t5-large
  task: text2text-generation

scenario:
  dataset_name: EnergyStarAI/summarization
  num_samples: 1000
  text_column_name: text
  truncation: True
  input_shapes:
    batch_size: 1
  dataset_prefix1: 'summarize: '
  t5_task: summarization

  generate_kwargs:
    max_new_tokens: 10
    min_new_tokens: 10
