defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: summarization

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: sshleifer/distilbart-cnn-12-6
  task: summarization

scenario:
  dataset_name: EnergyStarAI/summarization
  num_samples: 1000
  text_column_name: text
  truncation: True
  input_shapes:
    batch_size: 1

  generate_kwargs:
    max_length: 10
    min_new_tokens: 10
