defaults:
  - backend: pytorch # default backend
  - launcher: process # default launcher
  - benchmark: energy_star # default benchmark
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: text_generation_aya101

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: CohereForAI/aya-101
  task: text-generation

benchmark:
  dataset_name: EnergyStarAI/text_generation
  num_samples: 1000
  text_column_name: text
  truncation: True
  input_shapes:
    batch_size: 1

  generate_kwargs:
    max_new_tokens: 10
    min_new_tokens: 10

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/${experiment_name}
  sweep:
    # where to store sweep results
    dir: sweeps/${experiment_name}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      # set environment variable OVERRIDE_BENCHMARKS to 1
      # to not skip benchmarks that have been run before
      OVERRIDE_BENCHMARKS: 1
