defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: text_generation

launcher:
  device_isolation: False
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: facebook/opt-125m
  processor: facebook/opt-125m
  task: text-generation

scenario:
  dataset_name: EnergyStarAI/text_generation
  num_samples: 1000
  text_column_name: text
  truncation: True
  input_shapes:
    batch_size: 1

  generate_kwargs:
    max_new_tokens: 10
    min_new_tokens: 10
