defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: text_classification

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: lvwerra/distilbert-imdb
  processor: lvwerra/distilbert-imdb
  task: text-classification

scenario:
  dataset_name: EnergyStarAI/text_classification
  num_samples: 1000
  text_column_name: text
  truncation: True
  input_shapes:
    batch_size: 1
