defaults:
  - benchmark
  - scenario: inference
  - backend: openvino
  - launcher: process
  - _base_
  - _self_

name: openvino_diffusion

backend:
  half: true
  device: cpu
  export: true
  model: stabilityai/stable-diffusion-2-1

scenario:
  input_shapes:
    batch_size: 1
