defaults:
  - benchmark
  - scenario: inference
  - backend: openvino
  - launcher: process
  - _base_
  - _self_

name: openvino_static_quant

backend:
  device: cpu
  reshape: true
  no_weights: true
  load_in_8bit: true
  model: google-bert/bert-base-uncased

scenario:
  input_shapes:
    batch_size: 1
    sequence_length: 16
