defaults:
  - benchmark
  - backend: tensorrt-llm
  - scenario: inference
  - launcher: process
  - _base_
  - _self_

name: cuda_trt_llama

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  model: TinyLlama/TinyLlama-1.1B-Chat-v1.0

scenario:
  input_shapes:
    batch_size: 4
    sequence_length: 64

  generate_kwargs:
    max_new_tokens: 32
    min_new_tokens: 32
