defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: vllm
  - _base_
  - _self_

name: cuda_vllm_llama

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  serving_mode: online # server-like
  model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
  engine_args:
    enforce_eager: true # remove for better perf but bigger memory footprint

scenario:
  input_shapes:
    batch_size: 4
    sequence_length: 64

  generate_kwargs:
    max_new_tokens: 32
    min_new_tokens: 32
