defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: cuda_pytorch_llama

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  no_weights: true
  torch_dtype: float16
  model: TinyLlama/TinyLlama-1.1B-Chat-v1.0

scenario:
  memory: true
  latency: true

  warmup_runs: 10
  iterations: 10
  duration: 10

  input_shapes:
    batch_size: 1
    sequence_length: 256
  generate_kwargs:
    max_new_tokens: 32
    min_new_tokens: 32
