defaults:
  - benchmark
  - backend: pytorch
  - launcher: process
  - scenario: energy_star
  - _base_
  - _self_

name: energy_star

backend:
  model: gpt2
  device: cuda
  device_ids: 0
  no_weights: true
  task: feature-extraction

launcher:
  device_isolation: true

scenario:
  dataset_name: wikitext
  dataset_config: wikitext-2-raw-v1
  num_samples: 10
  input_shapes:
    batch_size: 1
