defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: ipex
  - _base_
  - _self_

name: ipex_llama

launcher:
  numactl: true
  numactl_kwargs:
    cpunodebind: 0
    membind: 0

scenario:
  latency: true
  memory: true

  warmup_runs: 10
  iterations: 10
  duration: 10
  
  input_shapes:
    batch_size: 1
    sequence_length: 256
  generate_kwargs:
    max_new_tokens: 32
    min_new_tokens: 32

backend:
  device: cpu
  export: true
  no_weights: true
  torch_dtype: bfloat16
  model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
