defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: ipex
  - _base_
  - _self_

name: ipex_bert

launcher:
  numactl: true
  numactl_kwargs:
    cpunodebind: 0
    membind: 0

scenario:
  latency: true
  memory: true
  input_shapes:
    batch_size: 1
    sequence_length: 128

backend:
  device: cpu
  no_weights: false
  export: true
  torch_dtype: bfloat16
  model: bert-base-uncased
