defaults:
  - benchmark
  - backend: neural-compressor
  - scenario: inference
  - launcher: process
  - _base_
  - _self_

name: neural_compressor_ptq_bert

backend:
  device: cpu
  no_weights: true
  model: bert-base-uncased
  ptq_quantization: true
  calibration: true

scenario:
  input_shapes:
    batch_size: 1
