defaults:
  - backend: openvino
  - launcher: process
  - benchmark: inference
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: openvino_static_quant_bert
model: bert-base-uncased
device: cpu

backend:
  export: true
  no_weights: true
  quantization: true
  calibration: true
  reshape: true

benchmark:
  input_shapes:
    batch_size: 1

hydra:
  run:
    dir: runs/${experiment_name}
  sweep:
    dir: sweeps/${experiment_name}
  job:
    chdir: true
    env_set:
      OVERRIDE_BENCHMARKS: 1
