defaults:
  - benchmark
  - scenario: inference
  - backend: openvino
  - launcher: process
  - _base_
  - _self_

name: openvino_static_quant_bert

backend:
  device: cpu
  no_weights: true
  model: bert-base-uncased
  quantization: true
  calibration: true
  reshape: true

scenario:
  input_shapes:
    batch_size: 1
