defaults:
  - backend: openvino
  - launcher: process
  - benchmark: inference
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

backend:
  device: cpu
  model: stabilityai/stable-diffusion-2-1
  experiment_name: openvino_diffusion
  reshape: true
  export: true
  half: true

benchmark:
  input_shapes:
    batch_size: 1

# hydra/cli specific settings
hydra:
  run:
    # where to store run results
    dir: runs/${experiment_name}
  sweep:
    # where to store sweep results
    dir: sweeps/${experiment_name}
  job:
    # change working directory to the run directory
    chdir: true
    env_set:
      # set environment variable OVERRIDE_BENCHMARKS to 1
      # to not skip benchmarks that have been run before
      OVERRIDE_BENCHMARKS: 1
