defaults:
  - backend: openvino
  - launcher: process
  - benchmark: inference
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

model: stabilityai/stable-diffusion-2-1

backend:
  experiment_name: openvino_diffusion
  export: true
  reshape: true
  half: true
  device: cpu

benchmark:
  input_shapes:
    batch_size: 1

hydra:
  run:
    dir: runs/${experiment_name}
  sweep:
    dir: sweeps/${experiment_name}
  job:
    chdir: true
    env_set:
      OVERRIDE_BENCHMARKS: 1
