defaults:
  - benchmark
  - scenario: inference
  - backend: openvino
  - launcher: process
  - _base_
  - _self_

name: openvino_diffusion

backend:
  device: cpu
  model: stabilityai/stable-diffusion-2-1
  reshape: true
  export: true
  half: true

scenario:
  input_shapes:
    batch_size: 1
