defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: pytorch_bert

launcher:
  device_isolation: true
  device_isolation_action: warn

scenario:
  latency: true
  memory: true
  input_shapes:
    batch_size: 1
    sequence_length: 128

backend:
  device: cuda
  device_ids: 0
  no_weights: true
  model: bert-base-uncased
