defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: pytorch_llama

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  model: gpt2
  device: cuda
  torch_dtype: float16

scenario:
  memory: true
  latency: true

  warmup_runs: 10
  iterations: 10
  duration: 10

  input_shapes:
    batch_size: 1
    sequence_length: 256
  generate_kwargs:
    max_new_tokens: 32
    min_new_tokens: 32
