defaults:
  - benchmark
  - scenario: inference
  - launcher: inline
  - backend: py-txi
  - _self_

name: tei_bert

backend:
  device: cpu
  model: bert-base-uncased

scenario:
  input_shapes:
    batch_size: 64
    sequence_length: 128
