defaults:
  - benchmark
  - scenario: inference
  - launcher: inline
  - backend: py-txi
  - _self_

name: tei_bert

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cpu
  model: BAAI/bge-base-en-v1.5

scenario:
  input_shapes:
    batch_size: 64
    sequence_length: 128
