defaults:
  - base_config # inherits from base config
  - _self_ # for hydra 1.1 compatibility
  - override backend: text-generation-inference

experiment_name: tgi

model: NousResearch/Llama-2-7b-hf
device: cuda

backend:
  initial_isolation_check: false
  continous_isolation_check: false
  torch_dtype: float16

benchmark:
  input_shapes:
    batch_size: 2
    sequence_length: 1

  new_tokens: 1000
