defaults:
  - backend: text-generation-inference # default backend
  - benchmark: inference # default benchmark
  - launcher: inline # default launcher
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: tgi_llama
model: TheBloke/Llama-2-70B-AWQ
device: cuda

backend:
  sharded: false
  quantization_scheme: awq
  # no_weights: true # wok in progress

benchmark:
  input_shapes:
    batch_size: 1
    sequence_length: 256
  new_tokens: 1000

hydra:
  run:
    dir: runs/${experiment_name}
  sweep:
    dir: sweeps/${experiment_name}
  job:
    chdir: true
    env_set:
      OVERRIDE_BENCHMARKS: 1
      CUDA_VISIBLE_DEVICES: 0
      CUDA_DEVICE_ORDER: PCI_BUS_ID
