defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: vllm
  - _base_
  - _self_

name: vllm_llama

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 0
  no_weights: false
  serving_mode: offline
  model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
  engine_args:
    enforce_eager: true

scenario:
  input_shapes:
    batch_size: 4
    sequence_length: 256
  generate_kwargs:
    max_new_tokens: 100
    min_new_tokens: 100
