defaults:
  - _base_
  - _self_

experiment_name: awq-batch_size(${benchmark.input_shapes.batch_size})-sequence_length(${benchmark.input_shapes.sequence_length})-new_tokens(${benchmark.new_tokens})
model: ybelkada/test-mistral-7b-v0.1-awq
