name: Build Images

on:
  workflow_dispatch:
  push:
    paths:
      - "docker/**"
      - ".github/workflows/build_images.yaml"
    branches:
      - build_images_*

    branches:
      - build_images_*

  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: build_images
  cancel-in-progress: true

jobs:
  build_and_save_cuda_images:
    strategy:
      fail-fast: false
      matrix:
        image:
          [
            { torch_cuda: cu118, torch_pre_release: 0, cuda_version: 11.8.0 },
            { torch_cuda: cu121, torch_pre_release: 0, cuda_version: 12.1.1 },
          ]

    runs-on: [single-gpu, nvidia-gpu, a10, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List
        run: |
          mkdir -p /mnt/hf_cache/optimum_benchmark
          ls /mnt/hf_cache/optimum_benchmark -hl

      - name: Build
        run: docker build
          --build-arg TORCH_CUDA=${{ matrix.image.torch_cuda }}
          --build-arg CUDA_VERSION=${{ matrix.image.cuda_version }}
          --build-arg TORCH_PRE_RELEASE=${{ matrix.image.torch_pre_release }}
          --tag opt-bench-cuda:${{ matrix.image.cuda_version }}
          docker/cuda

      - name: Save
        run: |
          sudo apt-get update && sudo apt-get install -y pigz
          docker save opt-bench-cuda:${{ matrix.image.cuda_version }} | pigz --fast > /mnt/hf_cache/optimum_benchmark/cuda-${{ matrix.image.cuda_version }}.tar.gz

  build_rocm_images:
    strategy:
      fail-fast: false
      matrix:
        image:
          [{ torch_rocm: rocm5.7, torch_pre_release: 0, rocm_version: 5.7.1 }]

    runs-on: [amd-gpu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build
          --build-arg USER_ID=$(id -u)
          --build-arg GROUP_ID=$(id -g)
          --build-arg TORCH_ROCM=${{ matrix.image.torch_rocm }}
          --build-arg ROCM_VERSION=${{ matrix.image.rocm_version }}
          --build-arg TORCH_PRE_RELEASE=${{ matrix.image.torch_pre_release }}
          --tag opt-bench-rocm:${{ matrix.image.rocm_version }}
          docker/rocm
