name: Build and Publish Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - build-and-publish-images
    paths:
      - .github/workflows/build_and_publish_docker_images.yaml
      - docker/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/build_and_publish_docker_images.yaml
      - docker/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish_docker_image:
    strategy:
      fail-fast: true
      matrix:
        flavor: [cpu, cuda-11.8, cuda-12.1, rocm-5.7]

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.flavor }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # If pull request
      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.event_name == 'pull_request' }}
        id: meta-pr
        uses: docker/metadata-action@v4
        with:
          images: |
            registry.internal.huggingface.tech/api-inference/community/text-generation-inference
          tags: |
            type=raw,value=sha-${{ github.sha }}-${{ matrix.flavor }}

      # If main, release or tag
      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.event_name != 'pull_request' }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}-${{ matrix.flavor }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.flavor }}
            type=raw,value=latest-${{ matrix.flavor }},enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=sha-${{ github.sha }}-${{ matrix.flavor }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/${{ matrix.flavor }}/Dockerfile
