name: Build and Publish Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker/**
      - .github/workflows/build_and_publish_docker_images.yaml
  schedule:
    - cron: "0 0 * * *"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish_docker_image:
    strategy:
      fail-fast: true
      matrix:
        image_flavor: [cpu, cuda, cuda-ort, rocm]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker images
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest-${{ matrix.image_flavor }}
            type=raw,value=sha-${{ github.sha }}-${{ matrix.image_flavor }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/${{ matrix.image_flavor }}/Dockerfile
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-${{ matrix.image_flavor }}
