name: Quality checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_cpu_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install quality requirements
        run: |
          pip install --upgrade pip
          pip install -e .[quality]

      - name: Check style with black
        run: |
          black --check .

      - name: Check style with ruff
        run: |
          ruff .
