name: CLI ROCm Pytorch Single-GPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  REGISTRY: ghcr.io
  IMAGE_FLAVOR: rocm
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run_cli_rocm_pytorch_single_gpu_tests:
    runs-on: [single-gpu, amd-gpu, mi250, ci]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set target devices
        run: |
          echo "DEVICE: $DEVICE"
          echo "DEVICE=$DEVICE" >> $GITHUB_ENV

      - name: Set docker image
        run: |
          if [ -z "${{ github.event.pull_request.number }}" ]; then
            IMAGE=$REGISTRY/$IMAGE_NAME:latest-$IMAGE_FLAVOR
          else
            IMAGE=$REGISTRY/$IMAGE_NAME:pr-${{ github.event.pull_request.number }}-$IMAGE_FLAVOR
          fi
          echo "IMAGE: $IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Run tests
        uses: addnab/docker-run-action@v3
        env:
          IMAGE: ${{ env.IMAGE }}
          DEVICE: ${{ env.DEVICE }}
        with:
          image: ${{ env.IMAGE }}
          options: |
            --rm
            --shm-size 64G
            --device /dev/kfd
            --device /dev/dri/${{ env.DEVICE }}
            --volume ${{ github.workspace }}:/workspace
            --workdir /workspace
          run: |
            pip install -e .[testing,diffusers,timm,peft,autoawq-rocm,auto-gptq-rocm]
            pytest -x -s -k "cli and cuda and pytorch and not (dp or ddp or device_map or deepspeed) and not (bnb or awq)"
