name: API ROCm Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_api_rocm_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'api') ||
      contains( github.event.pull_request.labels.*.name, 'rocm') ||
      contains( github.event.pull_request.labels.*.name, 'api_rocm')
      }}

    runs-on: [self-hosted, amd-gpu, single-gpu]

    container:
      image: ghcr.io/huggingface/optimum-benchmark:latest-rocm
      options:
        $(echo $(ls /dev/dri/ | grep render | awk -v indices="$ROCR_VISIBLE_DEVICES" 'BEGIN{split(indices, idx, ",")} {for (i in idx) if (NR == idx[i] + 1) print "--device /dev/dri/" $0}'))
        --group-add video
        --device /dev/kfd
        --ipc host
        --pid host

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ROCm-SMI
        run: |
          rocm-smi

      - name: Install dependencies
        run: |
          pip install -e .[testing,timm,diffusers,codecarbon]

      - name: Run tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PUSH_REPO_ID: optimum-benchmark/rocm
        run: |
          pytest tests/test_api.py -x -s -k "api and cuda"
