name: API CUDA Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_image_and_run_api_cuda_tests:
    strategy:
      fail-fast: false
      matrix:
        image:
          [{ torch_cuda: cu121, torch_pre_release: 0, cuda_version: 12.1.1 }]

    runs-on: [single-gpu, nvidia-gpu, a10, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          file: docker/cuda.dockerfile
          tags: opt-bench-cuda:${{ matrix.image.cuda_version }}
          cache-from: type=local,src=/mnt/hf_cache/opt_bench_cache/
          build-args: |
            TORCH_CUDA=${{ matrix.image.torch_cuda }}
            CUDA_VERSION=${{ matrix.image.cuda_version }}
            TORCH_PRE_RELEASE=${{ matrix.image.torch_pre_release }}

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: opt-bench-cuda:${{ matrix.image.cuda_version }}
          options: --rm --gpus all --shm-size 64G -e USE_CUDA="1" -e PROCESS_SPECIFIC_VRAM="0" -v $(pwd):/workspace -w /workspace
          run: |
            pip install -e .[testing,timm,diffusers]
            pytest -s -v -k 'api and cuda' -x
