name: CLI CUDA TensorRT-LLM Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  cli_cuda_tensorrt_llm_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'cli') ||
      contains( github.event.pull_request.labels.*.name, 'cuda') ||
      contains( github.event.pull_request.labels.*.name, 'tensorrt_llm') ||
      contains( github.event.pull_request.labels.*.name, 'cli_cuda_tensorrt_llm')
      }}

    runs-on: [single-gpu, nvidia-gpu, a10, ci]

    container:
      image: huggingface/optimum-nvidia:latest
      options: --gpus all --volume /mnt/cache/.cache/huggingface:/mnt/cache/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing]

      - name: Run tests
        run: |
          pytest -x -s -k "cli and cuda and tensorrt_llm"
