name: CLI CUDA Pytorch Multi-GPU Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_image_and_run_cli_cuda_pytorch_multi_gpu_tests:
    strategy:
      fail-fast: false
      matrix:
        image:
          [{ torch_cuda: cu121, torch_pre_release: 0, cuda_version: 12.1.1 }]

    runs-on: [multi-gpu, nvidia-gpu, 4-a10, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load image
        run: |
          docker load < /mnt/hf_cache/optimum_benchmark/cuda-${{ matrix.image.cuda_version }}.tar.gz

      - name: Run tests
        run: docker run
          --rm
          --gpus all
          --shm-size 64G
          --env USE_CUDA="1"
          --env PROCESS_SPECIFIC_VRAM="0"
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          --entrypoint /bin/bash
          opt-bench-cuda:${{ matrix.image.cuda_version }}
          -c "pip install -e .[testing,diffusers,timm,peft,deepspeed] &&
          pytest -s -v -k 'cli and cuda and pytorch and (dp or ddp or device_map or deepspeed)' -x"
