name: API CPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test_api_cpu.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test_api_cpu.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_api_cpu_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install -e .[testing,timm,diffusers,codecarbon]

      - name: Run tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PUSH_REPO_ID: optimum-benchmark/cpu
        run: |
          pytest -s -k "api and cpu"
