name: CLI Misc Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_cli_misc_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'cli') ||
      contains( github.event.pull_request.labels.*.name, 'misc') ||
      contains( github.event.pull_request.labels.*.name, 'cli_misc')
      }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, "macos-latest", windows-latest]
        python: ["3.8", "3.12"]

    name: OS ${{ matrix.os }} - Python ${{ matrix.python }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Linux packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y numactl

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install -e .[testing]

      - name: Run tests
        run: |
          pytest tests/test_cli.py -s -k "cli and not (cpu or cuda or rocm or mps)"
