name: CLI ROCm Pytorch Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_cli_rocm_pytorch_single_gpu_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'cli') ||
      contains( github.event.pull_request.labels.*.name, 'rocm') ||
      contains( github.event.pull_request.labels.*.name, 'pytorch') ||
      contains( github.event.pull_request.labels.*.name, 'single_gpu') ||
      contains( github.event.pull_request.labels.*.name, 'cli_rocm_pytorch_single_gpu')
      }}

    runs-on: [self-hosted, amd-gpu, single-gpu]

    container:
      image: ghcr.io/huggingface/optimum-benchmark:latest-rocm
      options: --ipc host
        --group-add video
        --device /dev/kfd
        --device /dev/dri
        --env ROCR_VISIBLE_DEVICES

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing,diffusers,timm,peft,autoawq,auto-gptq]

      - name: Run tests
        run: |
          pytest tests/test_cli.py -x -s -k "cli and cuda and pytorch and not (dp or ddp or device_map or deepspeed) and not bnb"

  run_cli_rocm_pytorch_multi_gpu_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'cli') ||
      contains( github.event.pull_request.labels.*.name, 'rocm') ||
      contains( github.event.pull_request.labels.*.name, 'pytorch') ||
      contains( github.event.pull_request.labels.*.name, 'multi_gpu') ||
      contains( github.event.pull_request.labels.*.name, 'cli_rocm_pytorch_multi_gpu')
      }}

    runs-on: [self-hosted, amd-gpu, multi-gpu]

    container:
      image: ghcr.io/huggingface/optimum-benchmark:latest-rocm
      options: --ipc host
        --group-add video
        --device /dev/kfd
        --device /dev/dri
        --env ROCR_VISIBLE_DEVICES

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing,diffusers,timm,deepspeed,peft,autoawq,auto-gptq] "deepspeed<0.15"

      - name: Run tests
        run: |
          FORCE_SERIAL=1 pytest tests/test_cli.py -x -s -k "cli and cuda and pytorch and (dp or ddp or device_map or deepspeed) and not bnb"
