name: Examples Folder CUDA TensorRT-LLM Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_examples_cuda_tensorrt_llm_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'examples') ||
      contains( github.event.pull_request.labels.*.name, 'cuda') ||
      contains( github.event.pull_request.labels.*.name, 'tensorrt_llm') ||
      contains( github.event.pull_request.labels.*.name, 'examples_cuda_tensorrt_llm')
      }}

    runs-on:
      group: aws-g5-4xlarge-plus

    container:
      image: huggingface/optimum-nvidia:latest
      options: --ipc host --gpus all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing]

      - name: Run tests
        run: |
          pytest tests/test_examples_folder.py -x -s -k "cuda and tensorrt_llm"
