name: CLI CUDA OnnxRuntime Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_image_and_run_cli_cuda_onnxruntime_tests:
    runs-on: nvidia-gpu
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build
          --file docker/cuda.dockerfile
          --build-arg USER_ID=$(id -u)
          --build-arg GROUP_ID=$(id -g)
          --build-arg CUDA_VERSION=11.8.0
          --build-arg TORCH_CUDA=cu118
          --tag opt-bench-cuda:11.8.0
          .

      - name: Get GPUs with most free memory
        id: get_devices
        run: |
          echo "::set-output name=devices::$(nvidia-smi --query-gpu=memory.free,index --format=csv,noheader,nounits | sort -n -k1 | tail -n 2 | awk -F', ' '{print $2}' | xargs echo -n | sed 's/ /,/g' | awk '{print $0}')"

      - name: Run tests
        run: docker run
          --rm
          --pid host
          --shm-size 64G
          --env USE_CUDA="1"
          --entrypoint /bin/bash
          --gpus '"device=${{ steps.get_devices.outputs.devices }}"'
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          opt-bench-cuda:11.8.0
          -c "pip install -e .[testing,onnxruntime-gpu,diffusers,timm] && pytest -k 'cli and cuda and onnxruntime' -x"
