name: API ROCm Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  REGISTRY: ghcr.io
  IMAGE_FLAVOR: rocm
  IMAGE_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  build_image_and_run_api_rocm_tests:
    runs-on: [single-gpu, amd-gpu, mi250, ci]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set target devices
        run: |
          echo "DEVICE: $DEVICE"
          echo "DEVICE=$DEVICE" >> $GITHUB_ENV

      - name: Set docker image
        run: |
          if [ -z "${{ github.event.pull_request.number }}" ]; then
            IMAGE=$REGISTRY/$IMAGE_NAME:latest-$IMAGE_FLAVOR
          else
            IMAGE=$REGISTRY/$IMAGE_NAME:pr-${{ github.event.pull_request.number }}-$IMAGE_FLAVOR
          fi
          echo "IMAGE: $IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Run tests
        uses: addnab/docker-run-action@v3
        env:
          IMAGE: ${{ env.IMAGE }}
          DEVICE: ${{ env.DEVICE }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PUSH_REPO_ID: optimum-benchmark/rocm
        with:
          image: ${{ env.IMAGE }}
          options: |
            --rm
            --shm-size 64G
            --env HF_TOKEN
            --env PUSH_REPO_ID
            --device /dev/kfd/
            --device /dev/dri/${{ env.DEVICE }}
            --volume ${{ github.workspace }}:/workspace
            --workdir /workspace
          run: |
            pip install -e .[testing,timm,diffusers,codecarbon]
            pytest -s -x -k "api and cuda"
