name: CLI ROCm Pytorch Multi-GPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test_cli_rocm_pytorch_multi_gpu.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test_cli_rocm_pytorch_multi_gpu.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_cli_rocm_pytorch_multi_gpu_tests:
    runs-on: [self-hosted, amd-gpu, multi-gpu]

    container:
      image: ghcr.io/huggingface/optimum-benchmark:latest-rocm
      options: --ipc host
        --shm-size "16gb"
        --group-add video
        --device /dev/kfd
        --device /dev/dri
        --env ROCR_VISIBLE_DEVICES
        --env HIP_VISIBLE_DEVICES=0,1
        --volume /mnt/cache/.cache/huggingface:/mnt/cache/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing,diffusers,timm,deepspeed,peft,autoawq,auto-gptq] "deepspeed<0.15"

      - name: Run tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PUSH_REPO_ID: optimum-benchmark/rocm
        run: |
          pytest -x -s -k "cli and cuda and pytorch and (dp or ddp or device_map or deepspeed) and not (bnb or awq)"
