name: CLI CUDA Pytorch Multi-GPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_cli_cuda_pytorch_multi_gpu_tests:
    if: ${{ (github.event_name == 'workflow_dispatch') || (github.event_name == 'push') || contains( github.event.pull_request.labels.*.name, 'cuda') }}

    runs-on: [multi-gpu, nvidia-gpu, 4-a10, ci]

    container:
      image: ghcr.io/huggingface/optimum-benchmark:latest-cuda
      options: --gpus all --volume /mnt/cache/.cache/huggingface:/mnt/cache/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing,diffusers,timm,peft,deepspeed]

      - name: Run tests
        run: |
          pytest -x -s -k "cli and cuda and pytorch and (dp or ddp or device_map or deepspeed)"
