name: CLI ROCm Pytorch Multi-GPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_cli_rocm_pytorch_multi_gpu_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'rocm') ||
      contains( github.event.pull_request.labels.*.name, 'pytorch')
      }}

    runs-on: [self-hosted, amd-gpu, multi-gpu]

    container:
      image: ghcr.io/huggingface/optimum-benchmark:latest-rocm
      options: --ipc host
        --group-add video
        --device /dev/kfd
        --device /dev/dri
        --env ROCR_VISIBLE_DEVICES
        --env HIP_VISIBLE_DEVICES=0,1
        --volume /mnt/cache/.cache/huggingface:/mnt/cache/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing,diffusers,timm,deepspeed,peft,autoawq,auto-gptq] "deepspeed<0.15"

      - name: Run tests
        run: |
          pytest -x -s -k "cli and cuda and pytorch and (dp or ddp or device_map or deepspeed) and not bnb"
