name: CLI CUDA Pytorch Multi-GPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  REGISTRY: ghcr.io
  IMAGE_FLAVOR: cuda
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run_cli_cuda_pytorch_multi_gpu_tests:
    runs-on: [multi-gpu, nvidia-gpu, 4-a10, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set docker image
        run: |
          if [ -z "${{ github.event.pull_request.number }}" ]; then
            IMAGE=$REGISTRY/$IMAGE_NAME:latest-$IMAGE_FLAVOR
          else
            IMAGE=$REGISTRY/$IMAGE_NAME:pr-${{ github.event.pull_request.number }}-$IMAGE_FLAVOR
          fi
          echo "IMAGE: $IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Run tests
        uses: addnab/docker-run-action@v3
        env:
          IMAGE: ${{ env.IMAGE }}
        with:
          image: ${{ env.IMAGE }}
          options: |
            --rm
            --gpus all
            --shm-size 64G
            --env MKL_THREADING_LAYER=GNU
            --volume ${{ github.workspace }}:/workspace
            --workdir /workspace
          run: |
            pip install -e .[testing,diffusers,timm,peft,deepspeed]
            pytest -x -s -k "cli and cuda and pytorch and (dp or ddp or device_map or deepspeed)"
