name: CLI CUDA vLLM Single-GPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test_cli_cuda_vllm.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test_cli_cuda_vllm.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  IMAGE:

jobs:
  run_cli_cuda_pytorch_tests:
    if: ${{ (github.event_name == 'workflow_dispatch') || contains( github.event.pull_request.labels.*.name, 'cuda') }}

    runs-on: [single-gpu, nvidia-gpu, a10, ci]

    container:
      image: ghcr.io/huggingface/optimum-benchmark:latest-cuda
      options: --gpus all --volume /mnt/cache/.cache/huggingface:/mnt/cache/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing,vllm,flash-attn]

      - name: Run tests
        env:
          FORCE_SERIAL: 1
        run: |
          pytest -x -s -k "cli and cuda and vllm"
