name: OnnxRuntime CUDA Inference Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Restore files ownership
        run: docker run
          --rm
          --entrypoint /bin/bash
          --env HOST_UID=`id -u`
          --env HOST_GID=`id -g`
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          ubuntu
          -c 'chown -R ${HOST_UID}:${HOST_GID} /workspace/optimum-benchmark'

      - name: Checkout
        uses: actions/checkout@v2

<<<<<<< HEAD:.github/workflows/test_gpu.yaml
      - name: Build GPU Docker image
        run: docker build --no-cache --build-arg CACHEBUST=$(date +%s) -f docker/gpu.dockerfile -t optimum-benchmark-gpu .

      - name: Run GPU tests
=======
      - name: Run tests
>>>>>>> seperated backend-device tests and update setup.py:.github/workflows/test_cuda_onnxruntime_inference.yaml
        run: docker run
          --rm
          --entrypoint /bin/bash
          --gpus '"device=0,1"'
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          optimum-benchmark-gpu
          -c "pip install -e .[test] && pytest -k '(cuda or tensorrt) and not onnxruntime_training' -x"
