name: CLI ROCm Pytorch Single-GPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test_cli_rocm_pytorch_single_gpu.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test_cli_rocm_pytorch_single_gpu.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

env:
  REGISTRY: ghcr.io
  IMAGE_FLAVOR: rocm
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run_cli_rocm_pytorch_single_gpu_tests:
    runs-on: [single-gpu, amd-gpu, mi250, ci]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set target devices
        run: |
          echo "DEVICE: $DEVICE"
          echo "DEVICE=$DEVICE" >> $GITHUB_ENV

      - name: Set docker image
        run: |
          echo "IMAGE: $REGISTRY/$IMAGE_NAME:latest-$IMAGE_FLAVOR"
          echo "IMAGE=$REGISTRY/$IMAGE_NAME:latest-$IMAGE_FLAVOR" >> $GITHUB_ENV

      - name: Unroot docker image
        env:
          IMAGE: ${{ env.IMAGE }}
        run: |
          docker build --build-arg IMAGE=$IMAGE --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t $IMAGE-unroot docker/unroot
          echo "IMAGE: $IMAGE-unroot"
          echo "IMAGE=$IMAGE-unroot" >> $GITHUB_ENV

      - name: Run tests
        uses: addnab/docker-run-action@v3
        env:
          IMAGE: ${{ env.IMAGE }}
          DEVICE: ${{ env.DEVICE }}
          WORKSPACE: ${{ github.workspace }}
        with:
          image: ${{ env.IMAGE }}
          options: |
            --rm
            --shm-size 64G
            --device /dev/kfd
            --device /dev/dri/${{ env.DEVICE }}
            --volume ${{ env.WORKSPACE }}:/workspace
            --workdir /workspace
          run: |
            pip install -e .[testing,diffusers,timm,peft,autoawq-rocm,auto-gptq-rocm]
            pytest -x -s -k "cli and cuda and pytorch and not (dp or ddp or device_map or deepspeed) and not (bnb or awq)"
