name: CLI CUDA Pytorch Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_image_and_run_cli_cuda_pytorch_tests:
    strategy:
      fail-fast: false
      matrix:
        image:
          [
            { torch_cuda: cu118, torch_pre_release: 0, cuda_version: 11.8.0 },
            { torch_cuda: cu121, torch_pre_release: 1, cuda_version: 12.1.1 },
          ]

    runs-on: [multi-gpu, nvidia-gpu, 4-a10, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build
          --file docker/cuda.dockerfile
          --build-arg USER_ID=$(id -u)
          --build-arg GROUP_ID=$(id -g)
          --build-arg TORCH_CUDA=${{ matrix.image.torch_cuda }}
          --build-arg CUDA_VERSION=${{ matrix.image.cuda_version }}
          --tag opt-bench-cuda:${{ matrix.image.cuda_version }}
          .

      - name: Run tests
        run: docker run
          --rm
          --gpus all
          --shm-size 64G
          --env USE_CUDA="1"
          --env PROCESS_SPECIFIC_VRAM="0"
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          --entrypoint /bin/bash
          opt-bench-cuda:${{ matrix.image.cuda_version }}
          -c "pip install requests && pip install -e .[testing,diffusers,timm,deepspeed,peft,bitsandbytes,autoawq,auto-gptq-${{ matrix.image.torch_cuda }}] && pytest -k 'cli and cuda and pytorch' -x"