name: CLI ROCm Pytorch Multi-GPU Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_image_and_run_cli_rocm_pytorch_multi_gpu_tests:
    strategy:
      fail-fast: false
      matrix:
        image:
          [{ torch_rocm: rocm5.7, torch_pre_release: 0, rocm_version: 5.7.1 }]

    runs-on: [amd-gpu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: docker run
          --rm
          --pid host
          --shm-size 64G
          --env USE_ROCM="1"
          --device /dev/kfd
          --device /dev/dri/renderD130
          --device /dev/dri/renderD131
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          --entrypoint /bin/bash
          opt-bench-rocm:${{ matrix.image.rocm_version }}
          -c "pip install -e .[testing,diffusers,timm,deepspeed,peft,autoawq-rocm,auto-gptq-rocm] &&
          pytest -k 'cli and cuda and pytorch and (dp or ddp or device_map or deepspeed) and not bnb' -x"
