name: API Misc Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_api_misc_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'api') ||
      contains( github.event.pull_request.labels.*.name, 'misc') ||
      contains( github.event.pull_request.labels.*.name, 'api_misc')
      }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, "macos-latest", windows-latest]
        python: ["3.8", "3.12"]

    name: OS ${{ matrix.os }} - Python ${{ matrix.python }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install -e .[testing,timm,diffusers,codecarbon]

      - name: Run tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PUSH_REPO_ID: optimum-benchmark/misc-${{ matrix.os }}-${{ matrix.python }}
        run: |
          pytest -s -k "api and not (cpu or cuda or rocm or mps)"
