name: Pytorch RoCm Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: hf-amd-mi210-dev
    steps:
      - name: Restore files ownership
        run: docker run
          --rm
          --entrypoint /bin/bash
          --env HOST_UID=`id -u`
          --env HOST_GID=`id -g`
          --volume $(pwd):/workspace/optimum-benchmark
          --workdir /workspace/optimum-benchmark
          ubuntu
          -c 'chown -R ${HOST_UID}:${HOST_GID} /workspace/optimum-benchmark'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build 
            --file docker/rocm.dockerfile 
            --tage opt-bench-rocm 
            .

      - name: Run tests
        run: |
          docker run
            --rm
            --device /dev/kfd
            --device /dev/dri
            --entrypoint /bin/bash
            --shm-size=64G
            --volume $(pwd):/workspace/optimum-benchmark
            --workdir /workspace/optimum-benchmark
            --env USE_ROCM="1"
            opt-bench-rocm:latest
            -c "pip install -e .[test,peft,diffusers] && pytest -k 'cuda and pytorch' -x"
