name: CLI CUDA Py-TXI Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_cli_cuda_py_txi_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'cli') ||
      contains( github.event.pull_request.labels.*.name, 'cuda') ||
      contains( github.event.pull_request.labels.*.name, 'py_txi') ||
      contains( github.event.pull_request.labels.*.name, 'cli_cuda_py_txi')
      }}

    runs-on: [single-gpu, nvidia-gpu, a10, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -e .[testing,py-txi]

      - name: Run tests
        run: pytest tests/test_cli.py -x -s -k "cli and cuda and py_txi"
