name: CLI CUDA Pytorch Single-GPU Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_cli_cuda_pytorch_single_gpu_tests:
    runs-on: [single-gpu, nvidia-gpu, a10, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull image
        run: docker pull pytorch/pytorch:2.2.2-cuda12.1-cudnn8-devel

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: pytorch/pytorch:2.2.2-cuda12.1-cudnn8-devel
          options: |
            --rm
            --gpus all
            --shm-size 64G
            --env MKL_THREADING_LAYER=GNU
            --volume ${{ github.workspace }}:/workspace
            --workdir /workspace
          run: |
            pip install -e .[testing,diffusers,timm,peft,bitsandbytes,autoawq,auto-gptq]
            pytest -x -s -k "cli and cuda and pytorch and not (dp or ddp or device_map or deepspeed) and not (awq)"
