name: API ROCm Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test_api_rocm.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test_api_rocm.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_api_rocm_tests:
    runs-on: [self-hosted, amd-gpu, single-gpu]

    container:
      image: ghcr.io/huggingface/optimum-benchmark:latest-rocm
      options: --ipc host
        --shm-size "16gb"
        --group-add video
        --device /dev/kfd
        --device /dev/dri
        --env ROCR_VISIBLE_DEVICES
        --volume /mnt/cache/.cache/huggingface:/mnt/cache/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing,timm,diffusers,codecarbon]

      - name: Run tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PUSH_REPO_ID: optimum-benchmark/rocm
        run: |
          export HIP_VISIBLE_DEVICES=${ROCR_VISIBLE_DEVICES} && unset ROCR_VISIBLE_DEVICES
          pytest -s -x -k "api and cuda"
