name: CLI CUDA Pytorch Single-GPU Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cli_cuda_pytorch_single_gpu_tests:
    runs-on: [single-gpu, nvidia-gpu, a10, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        uses: addnab/docker-run-action@v3
        env:
          WORKSPACE: ${{ github.workspace }}
        with:
          image: pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime
          options: |
            --rm
            --gpus all
            --shm-size 64G
            --env USE_CUDA="1"
            --env PROCESS_SPECIFIC_VRAM="0"
            --volume $WORKSPACE:/workspace
            --workdir /workspace
          run: |
            pip install -e .[testing,diffusers,timm,peft,bitsandbytes,autoawq,auto-gptq]
            pytest -x -s -k "cli and cuda and pytorch and not (dp or ddp or device_map or deepspeed) and not (awq or torch_compile)"
