name: CLI CUDA vLLM Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  run_cli_cuda_pytorch_tests:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'cli') ||
      contains( github.event.pull_request.labels.*.name, 'cuda') ||
      contains( github.event.pull_request.labels.*.name, 'vllm') ||
      contains( github.event.pull_request.labels.*.name, 'cli_cuda_vllm')
      }}

    runs-on: [single-gpu, nvidia-gpu, a10, ci]

    container:
      image: ghcr.io/huggingface/optimum-benchmark:latest-cuda
      options: --gpus all --volume /mnt/cache/.cache/huggingface:/mnt/cache/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing,vllm,flash-attn]

      - name: Run tests
        env:
          FORCE_SERIAL: 1
        run: |
          pytest -x -s -k "cli and cuda and vllm"
