name: CLI CUDA TensorRT-LLM Single-GPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test_cli_cuda_tensorrt_llm.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test_cli_cuda_tensorrt_llm_single_gpu.yaml
      - "optimum_benchmark/**"
      - "docker/**"
      - "tests/**"
      - "setup.py"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  cli_cuda_tensorrt_llm_single_gpu_tests:
    if: ${{ (github.event_name == 'workflow_dispatch') || contains( github.event.pull_request.labels.*.name, 'trt-llm') }}

    name: CLI CUDA TensorRT-LLM Single-GPU Tests

    runs-on: [single-gpu, nvidia-gpu, a10, ci]

    container:
      image: huggingface/optimum-nvidia:latest
      options: --gpus all --volume /mnt/cache/.cache/huggingface:/mnt/cache/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -e .[testing]

      - name: Run tests
        run: |
          pytest -x -s -k "cli and cuda and tensorrt_llm"
