name: CLI CUDA Torch-ORT Multi-GPU Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  build_image_and_run_cli_cuda_torch_ort_multi_gpu_tests:
    runs-on: [multi-gpu, nvidia-gpu, 4-a10, ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/huggingface/optimum-benchmark:latest-cuda-ort
          options: |
            --rm
            --gpus all
            --shm-size 64G
            --env MKL_THREADING_LAYER=GNU
            --volume ${{ github.workspace }}:/workspace
            --workdir /workspace
          run: |
            pip install -e .[testing,torch-ort,peft]
            pytest -x -s -k "cli and cuda and torch_ort and (dp or ddp or device_map) and not peft"
